// Generated by gencpp from file learn_robot1_pkg/simple_programRequest.msg
// DO NOT EDIT!


#ifndef LEARN_ROBOT1_PKG_MESSAGE_SIMPLE_PROGRAMREQUEST_H
#define LEARN_ROBOT1_PKG_MESSAGE_SIMPLE_PROGRAMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learn_robot1_pkg
{
template <class ContainerAllocator>
struct simple_programRequest_
{
  typedef simple_programRequest_<ContainerAllocator> Type;

  simple_programRequest_()
    : a(0)
    , b(0)  {
    }
  simple_programRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simple_programRequest_

typedef ::learn_robot1_pkg::simple_programRequest_<std::allocator<void> > simple_programRequest;

typedef boost::shared_ptr< ::learn_robot1_pkg::simple_programRequest > simple_programRequestPtr;
typedef boost::shared_ptr< ::learn_robot1_pkg::simple_programRequest const> simple_programRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator1> & lhs, const ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator1> & lhs, const ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learn_robot1_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learn_robot1_pkg/simple_programRequest";
  }

  static const char* value(const ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simple_programRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learn_robot1_pkg::simple_programRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARN_ROBOT1_PKG_MESSAGE_SIMPLE_PROGRAMREQUEST_H
