// Generated by gencpp from file learn_robot1_pkg/simple_programResponse.msg
// DO NOT EDIT!


#ifndef LEARN_ROBOT1_PKG_MESSAGE_SIMPLE_PROGRAMRESPONSE_H
#define LEARN_ROBOT1_PKG_MESSAGE_SIMPLE_PROGRAMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learn_robot1_pkg
{
template <class ContainerAllocator>
struct simple_programResponse_
{
  typedef simple_programResponse_<ContainerAllocator> Type;

  simple_programResponse_()
    : sum(0)  {
    }
  simple_programResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simple_programResponse_

typedef ::learn_robot1_pkg::simple_programResponse_<std::allocator<void> > simple_programResponse;

typedef boost::shared_ptr< ::learn_robot1_pkg::simple_programResponse > simple_programResponsePtr;
typedef boost::shared_ptr< ::learn_robot1_pkg::simple_programResponse const> simple_programResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator1> & lhs, const ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator1> & lhs, const ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learn_robot1_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learn_robot1_pkg/simple_programResponse";
  }

  static const char* value(const ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"int64 sum\n"
;
  }

  static const char* value(const ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simple_programResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learn_robot1_pkg::simple_programResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARN_ROBOT1_PKG_MESSAGE_SIMPLE_PROGRAMRESPONSE_H
