// Generated by gencpp from file learn_robot1_pkg/simple_program.msg
// DO NOT EDIT!


#ifndef LEARN_ROBOT1_PKG_MESSAGE_SIMPLE_PROGRAM_H
#define LEARN_ROBOT1_PKG_MESSAGE_SIMPLE_PROGRAM_H

#include <ros/service_traits.h>


#include <learn_robot1_pkg/simple_programRequest.h>
#include <learn_robot1_pkg/simple_programResponse.h>


namespace learn_robot1_pkg
{

struct simple_program
{

typedef simple_programRequest Request;
typedef simple_programResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simple_program
} // namespace learn_robot1_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learn_robot1_pkg::simple_program > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learn_robot1_pkg::simple_program&) { return value(); }
};

template<>
struct DataType< ::learn_robot1_pkg::simple_program > {
  static const char* value()
  {
    return "learn_robot1_pkg/simple_program";
  }

  static const char* value(const ::learn_robot1_pkg::simple_program&) { return value(); }
};


// service_traits::MD5Sum< ::learn_robot1_pkg::simple_programRequest> should match
// service_traits::MD5Sum< ::learn_robot1_pkg::simple_program >
template<>
struct MD5Sum< ::learn_robot1_pkg::simple_programRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learn_robot1_pkg::simple_program >::value();
  }
  static const char* value(const ::learn_robot1_pkg::simple_programRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_robot1_pkg::simple_programRequest> should match
// service_traits::DataType< ::learn_robot1_pkg::simple_program >
template<>
struct DataType< ::learn_robot1_pkg::simple_programRequest>
{
  static const char* value()
  {
    return DataType< ::learn_robot1_pkg::simple_program >::value();
  }
  static const char* value(const ::learn_robot1_pkg::simple_programRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learn_robot1_pkg::simple_programResponse> should match
// service_traits::MD5Sum< ::learn_robot1_pkg::simple_program >
template<>
struct MD5Sum< ::learn_robot1_pkg::simple_programResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learn_robot1_pkg::simple_program >::value();
  }
  static const char* value(const ::learn_robot1_pkg::simple_programResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_robot1_pkg::simple_programResponse> should match
// service_traits::DataType< ::learn_robot1_pkg::simple_program >
template<>
struct DataType< ::learn_robot1_pkg::simple_programResponse>
{
  static const char* value()
  {
    return DataType< ::learn_robot1_pkg::simple_program >::value();
  }
  static const char* value(const ::learn_robot1_pkg::simple_programResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARN_ROBOT1_PKG_MESSAGE_SIMPLE_PROGRAM_H
